### ISSUE TITLE
Release OOS 13.1.0.501 kernel sources in accordance with GPL

### ISSUE THREAD

**Issue by chandu078** [OnePlusOSS/android_kernel_oneplus_sm8550#1]
@OnePlusOSSAdmin,  

Please do needful.

**Comment by OnePlusOSSAdmin** [comment]
We've released kernel code of 13.1.0.590. Please check branch oneplus/sm8550_t_13.1.0_oneplus11. And we would update it continuously as new software version release.

**Comment by chandu078** [comment]
> We've released kernel code of 13.1.0.590. Please check branch oneplus/sm8550_t_13.1.0_oneplus11. And we would update it continuously as new software version release.

Thank you, OnePlus team. I greatly appreciate it.
