### ISSUE TITLE
Kernel source for Oneplus 12R CPH2585

### ISSUE THREAD

**Issue by Venkat3620** [OnePlusOSS/android_kernel_oneplus_sm8550#4]
@OnePlusOSSAdmin Please release working kernel source code for Oneplus 12R with all requried modules and dts

**Comment by OnePlusOSSAdmin** [comment]
It will be released when we are back from festival leave

**Comment by cherinyy** [comment]
https://github.com/OnePlusOSS/android_kernel_oneplus_sm8550/tree/oneplus/sm8550_u_14.0.0_oneplus_12r

https://github.com/OnePlusOSS/android_kernel_oneplus_sm8550/tree/oneplus/sm8550_u_14.0.0_ace3

What is the difference between them?

**Comment by Venkat3620** [comment]
@OnePlusOSSAdmin 

can you please check the kernel modules and dts of camera
for oneplus12r , we tried both ace3 and oneplus12r sources.
when stock kernel is used its fine.

front camera seems to fail to start

Here is dmesg log camera fail

[    5.621743] [ T1306] CAM_INFO: CAM-SENSOR: cam_sensor_power_up_advance: 1159 Sensor Power up success for s5k3p9 sensor_id:0x3109, slave_addr:0x20
[    5.621820] [    C0] CAM_ERR: CAM-CCI: cam_cci_irq: 360 Base:0000000000000000, cci: 1, M1_Q1 NACK ERROR: 0x40000000
[    5.621829] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 252 ** CCI1_I2C_M1_Q1 register dump **
[    5.621833] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 255 ** CCI TOP Registers **
[    5.621838] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x0 value = 0x10070000
[    5.621843] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x4 value = 0x1
[    5.621849] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x8 value = 0x8
[    5.621854] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0xC value = 0x0
[    5.621858] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x10 value = 0x0
[    5.621863] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x14 value = 0x0
[    5.621867] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x18 value = 0x0
[    5.621872] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x1C value = 0x0
[    5.621876] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x20 value = 0x0
[    5.621881] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x24 value = 0x0
[    5.621883] [  T691] type=1400 audit(1708926785.858:88): avc:  denied  { read } for  comm="android.hardwar" name="type" dev="sysfs" ino=133618 scontext=u:r:hal_health_default:s0 tcontext=u:object_r:sysfs:s0 tclass=file permissive=0
[    5.621883] [ T1179] healthd: battery l=91 v=4220 t=34.6 h=1 st=4 c=842 fc=5500000 cc=5 chg=
[    5.621886] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x28 value = 0x0
[    5.621891] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x2C value = 0x0
[    5.621895] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x30 value = 0x0
[    5.621900] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 260 offset = 0x34 value = 0x0
[    5.621903] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 265 ** CCI1_I2C_M1 Registers **
[    5.621908] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 273 offset = 0x200 value = 0x100016
[    5.621912] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 273 offset = 0x204 value = 0x110012
[    5.621917] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 273 offset = 0x208 value = 0x10000F
[    5.621921] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 273 offset = 0x20C value = 0x18
[    5.621926] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 273 offset = 0x210 value = 0x33
[    5.621931] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 273 offset = 0x214 value = 0x1081F001
[    5.621935] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 273 offset = 0x21C value = 0x0
[    5.621940] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 273 offset = 0x220 value = 0x30
[    5.621943] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 278  ** CCI1_I2C_M1_Q1 Registers **
[    5.621949] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 284 offset = 0x600 value = 0x5
[    5.621953] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 284 offset = 0x604 value = 0x2
[    5.621958] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 284 offset = 0x608 value = 0x2B
[    5.621962] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 284 offset = 0x60C value = 0x0
[    5.621967] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 284 offset = 0x610 value = 0x7
[    5.621971] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 284 offset = 0x614 value = 0x3010
[    5.621976] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 284 offset = 0x618 value = 0x0

[    5.621979] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 288  **CCI Interrupt Registers**
[    5.621983] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 293 offset = 0xC00 value = 0x1
[    5.621991] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 293 offset = 0xC04 value = 0x7FFF7FF7
[    5.621996] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 293 offset = 0xC08 value = 0x40000000
[    5.622000] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 293 offset = 0xC0C value = 0x0
[    5.622005] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 293 offset = 0xC10 value = 0x110000
[    5.622010] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 293 offset = 0xC14 value = 0x0
[    5.622014] [    C0] CAM_INFO: CAM-CCI: cam_cci_dump_registers: 293 offset = 0xC18 value = 0x0
[    5.622086] [ T1306] CAM_ERR: CAM-CCI: cam_cci_read: 1615 CCI1_I2C_M1_Q1 ERROR with Slave 0x20
[    5.622090] [ T1306] CAM_ERR: CAM-CCI: cam_cci_read_bytes: 1978 CCI1_I2C_M1 Failed to read rc:-22
[    5.622093] [ T1306] CAM_ERR: CAM-SENSOR: cam_cci_i2c_read: 41 rc = -22
[    5.622095] [ T1306] CAM_WARN: CAM-SENSOR: cam_sensor_match_id: 958 s5k3p9 read id: 0x0 expected id 0x3109:||0x0:
**[    5.622097] [ T1306] CAM_INFO: CAM-SENSOR: cam_sensor_driver_cmd: 1172 Probe failed for s5k3p9 slot:3, slave_addr:0x20, sensor_id:0x3109**

**Comment by inferno0230** [comment]
>  [ 5.622095] [ T1306] CAM_WARN: CAM-SENSOR: cam_sensor_match_id: 958 s5k3p9 read id: 0x0 expected id 0x3109:||0x0:
[ 5.622097] [ T1306] CAM_INFO: CAM-SENSOR: cam_sensor_driver_cmd: 1172 Probe failed for s5k3p9 slot:3, slave_addr:0x20, sensor_id:0x3109

@OnePlusOSSAdmin

**Comment by inferno0230** [comment]
@OnePlusOSSAdmin Please respond.

**Comment by OnePlusOSSAdmin** [comment]
R&D team analysed it. It seems that it's because of abnormal hardware. Does the issue occur when using stock ROM?

**Comment by inferno0230** [comment]
> R&D team analysed it. It seems that it's because of abnormal hardware. Does the issue occur when using stock ROM?

Yes, There's no issue with front cam on stock ROM, and even on aosp it's works but only if we use dtb/o from stock ROM.

The dtb/o compiled from oss code release results in that probe error

**Comment by Venkat3620** [comment]
> R&D team analysed it. It seems that it's because of abnormal hardware. Does the issue occur when using stock ROM?

I tested with stock modules and kernel along with dtb and dtbo . Those seemed working fine on custom roms. Only issue was when i used oss modules and dtbs front camera doesnt show up

**Comment by OnePlusOSSAdmin** [comment]
Is this same with [issue 6 ](https://github.com/OnePlusOSS/android_kernel_oneplus_sm8550/issues/6)? If so, please close either one. 
You could send a mail to oss@oneplus.com. Then we provide the camera-devicetree changes based on qcom codebase tag.
We are preparing the latest kernel code release and would check this issue internally.

**Comment by inferno0230** [comment]
> Is this same with [issue 6 ](https://github.com/OnePlusOSS/android_kernel_oneplus_sm8550/issues/6)? If so, please close either one. You could send a mail to [oss@oneplus.com](mailto:oss@oneplus.com). Then we provide the camera-devicetree changes based on qcom codebase tag. We are preparing the latest kernel code release and would check this issue internally.

Yeah it is, I'll close the other issue for now. Please look into camera-devicetree changes. Thanks

**Comment by 7thripr** [comment]
@OnePlusOSSAdmin any update on this issue?

**Comment by muralivijay** [comment]
may i know how do you fixed the bug ? mine also front sensor not probe same NACK error . so the issue comes from module side or devicetree side ?
